version: 0.2

phases:
    install:
      commands:
        - echo "Install Dependencies"
        - yum -y install update
        - echo "Install Terraform on build server"
        - yum install -y yum-utils shadow-utils
        - yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
        - yum -y install terraform
    build:
      commands:
        - echo "Entered into Pre-Build Stage..."
        - cd infra/
        - echo "Initilize terraform infra"
        - terraform init
        - echo "Terraform Infra Plan"
        - terraform plan
        - echo "Deploy terraform infrastructure"
        - terraform apply --auto-approve