---
  - name: "Install Dependencies"
    hosts: web
    become: yes
    tasks:
       - name: "Install application dependencies"
         yum:
           name:
             - php
             - php-mysql
           state: present